# MQTT server parameters
mqtt:
  # Enable/disable mqtt transport protocol.
  enabled: true
  bind_address: 127.0.0.1
  bind_port: 1884
  adaptor: JsonMqttAdaptor
  timeout: 10000
  netty:
    leak_detector_level: DISABLED
    boss_group_thread_count: 1
    worker_group_thread_count: 12
    max_payload_size: 65536
  # MQTT SSL configuration
  ssl:
    # Enable/disable SSL support
    enabled: false
    # SSL protocol: See http://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html#SSLContext
    protocol: TLSv1.2
    # Path to the key store that holds the SSL certificate
    key_store: mqttserver.jks
    # Password used to access the key store
    key_store_password: server_ks_password
    # Password used to access the key
    key_password: server_key_password
    # Type of the key store
    key_store_type: JKS
spring:
  redis:
    host: localhost
    port: 6379
# Redis默认情况下有16个分片,这里配置具体使用的分片，默认为0
    database: 0
# 链接超时时间(毫秒)
    timeout: 3600ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间(使用负值表示限制) 默认为-1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
